/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as SpotifyCallbackRouteImport } from './routes/spotify.callback'
import { Route as AppWelcomeRouteImport } from './routes/_app.welcome'
import { Route as AppMasteringRouteImport } from './routes/_app.mastering'
import { Route as AppLibraryRouteImport } from './routes/_app.library'
import { Route as AppJournalRouteImport } from './routes/_app.journal'
import { Route as AppBeatmakerRouteImport } from './routes/_app.beatmaker'
import { Route as AppAssemblyRouteImport } from './routes/_app.assembly'
import { Route as AppAboutRouteImport } from './routes/_app.about'
import { Route as AppShareSetIdRouteImport } from './routes/_app.share.$setId'
import { Route as AppAssemblySetIdRouteImport } from './routes/_app.assembly_.$setId'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const SpotifyCallbackRoute = SpotifyCallbackRouteImport.update({
  id: '/spotify/callback',
  path: '/spotify/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWelcomeRoute = AppWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => AppRoute,
} as any)
const AppMasteringRoute = AppMasteringRouteImport.update({
  id: '/mastering',
  path: '/mastering',
  getParentRoute: () => AppRoute,
} as any)
const AppLibraryRoute = AppLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppBeatmakerRoute = AppBeatmakerRouteImport.update({
  id: '/beatmaker',
  path: '/beatmaker',
  getParentRoute: () => AppRoute,
} as any)
const AppAssemblyRoute = AppAssemblyRouteImport.update({
  id: '/assembly',
  path: '/assembly',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppShareSetIdRoute = AppShareSetIdRouteImport.update({
  id: '/share/$setId',
  path: '/share/$setId',
  getParentRoute: () => AppRoute,
} as any)
const AppAssemblySetIdRoute = AppAssemblySetIdRouteImport.update({
  id: '/assembly_/$setId',
  path: '/assembly/$setId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/about': typeof AppAboutRoute
  '/assembly': typeof AppAssemblyRoute
  '/beatmaker': typeof AppBeatmakerRoute
  '/journal': typeof AppJournalRoute
  '/library': typeof AppLibraryRoute
  '/mastering': typeof AppMasteringRoute
  '/welcome': typeof AppWelcomeRoute
  '/spotify/callback': typeof SpotifyCallbackRoute
  '/assembly/$setId': typeof AppAssemblySetIdRoute
  '/share/$setId': typeof AppShareSetIdRoute
}
export interface FileRoutesByTo {
  '/about': typeof AppAboutRoute
  '/assembly': typeof AppAssemblyRoute
  '/beatmaker': typeof AppBeatmakerRoute
  '/journal': typeof AppJournalRoute
  '/library': typeof AppLibraryRoute
  '/mastering': typeof AppMasteringRoute
  '/welcome': typeof AppWelcomeRoute
  '/spotify/callback': typeof SpotifyCallbackRoute
  '/': typeof AppIndexRoute
  '/assembly/$setId': typeof AppAssemblySetIdRoute
  '/share/$setId': typeof AppShareSetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/assembly': typeof AppAssemblyRoute
  '/_app/beatmaker': typeof AppBeatmakerRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/library': typeof AppLibraryRoute
  '/_app/mastering': typeof AppMasteringRoute
  '/_app/welcome': typeof AppWelcomeRoute
  '/spotify/callback': typeof SpotifyCallbackRoute
  '/_app/': typeof AppIndexRoute
  '/_app/assembly_/$setId': typeof AppAssemblySetIdRoute
  '/_app/share/$setId': typeof AppShareSetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/assembly'
    | '/beatmaker'
    | '/journal'
    | '/library'
    | '/mastering'
    | '/welcome'
    | '/spotify/callback'
    | '/assembly/$setId'
    | '/share/$setId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/assembly'
    | '/beatmaker'
    | '/journal'
    | '/library'
    | '/mastering'
    | '/welcome'
    | '/spotify/callback'
    | '/'
    | '/assembly/$setId'
    | '/share/$setId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/about'
    | '/_app/assembly'
    | '/_app/beatmaker'
    | '/_app/journal'
    | '/_app/library'
    | '/_app/mastering'
    | '/_app/welcome'
    | '/spotify/callback'
    | '/_app/'
    | '/_app/assembly_/$setId'
    | '/_app/share/$setId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  SpotifyCallbackRoute: typeof SpotifyCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/spotify/callback': {
      id: '/spotify/callback'
      path: '/spotify/callback'
      fullPath: '/spotify/callback'
      preLoaderRoute: typeof SpotifyCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/welcome': {
      id: '/_app/welcome'
      path: '/welcome'
      fullPath: '/welcome'
      preLoaderRoute: typeof AppWelcomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mastering': {
      id: '/_app/mastering'
      path: '/mastering'
      fullPath: '/mastering'
      preLoaderRoute: typeof AppMasteringRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/library': {
      id: '/_app/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AppLibraryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/beatmaker': {
      id: '/_app/beatmaker'
      path: '/beatmaker'
      fullPath: '/beatmaker'
      preLoaderRoute: typeof AppBeatmakerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assembly': {
      id: '/_app/assembly'
      path: '/assembly'
      fullPath: '/assembly'
      preLoaderRoute: typeof AppAssemblyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/share/$setId': {
      id: '/_app/share/$setId'
      path: '/share/$setId'
      fullPath: '/share/$setId'
      preLoaderRoute: typeof AppShareSetIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assembly_/$setId': {
      id: '/_app/assembly_/$setId'
      path: '/assembly/$setId'
      fullPath: '/assembly/$setId'
      preLoaderRoute: typeof AppAssemblySetIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppAssemblyRoute: typeof AppAssemblyRoute
  AppBeatmakerRoute: typeof AppBeatmakerRoute
  AppJournalRoute: typeof AppJournalRoute
  AppLibraryRoute: typeof AppLibraryRoute
  AppMasteringRoute: typeof AppMasteringRoute
  AppWelcomeRoute: typeof AppWelcomeRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAssemblySetIdRoute: typeof AppAssemblySetIdRoute
  AppShareSetIdRoute: typeof AppShareSetIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppAssemblyRoute: AppAssemblyRoute,
  AppBeatmakerRoute: AppBeatmakerRoute,
  AppJournalRoute: AppJournalRoute,
  AppLibraryRoute: AppLibraryRoute,
  AppMasteringRoute: AppMasteringRoute,
  AppWelcomeRoute: AppWelcomeRoute,
  AppIndexRoute: AppIndexRoute,
  AppAssemblySetIdRoute: AppAssemblySetIdRoute,
  AppShareSetIdRoute: AppShareSetIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  SpotifyCallbackRoute: SpotifyCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
